export const jsonTest = {
  data: [
    {
      formid: 'items',
      title: 'Item Master',
      type: 'M',
      module: 'main',
      pkeys: 'item_name',
      pkeyid: 'item_id',
      model: null,
      extra_props: null,
      readonly: null,
      colsize: 'col-12',
      classes: null,
      hint: null,
      sortno: null,
      active: 1,
      formview: 'form',
      formfilter: null,
      description: null,
      formgroup: null,
      icon: null,
      sections: [
        {
          formid: 'items',
          sectionid: 'heading1',
          title: 'heading1',
          readonly: null,
          colsize: 'col-12',
          classes: null,
          hint: null,
          sortno: 1,
          active: 1,
          columns: [
            {
              formid: 'items',
              sectionid: 'heading1',
              field: 'item_name',
              title: 'Item Name',
              colsize: 'col-6',
              type: 'string',
              component: 'input',
              required: 1,
              sortno: 1,
              active: 1,
              formview: 1,
              listview: 1,
              selectqry: null,
              options: null,
              defaultvalue: null,
              addattrs: {
                validation: {
                  pattern: '^[a-zA-Z\\s]+$',
                  errorMessage:
                    'Only letters and spaces are allowed. Please use only allowed cases Thank You. :)',
                },
              },
              readonly: null,
              hidden: null,
              classes: null,
              inline: null,
              placeholder: null,
              hint: 'Please Enter Item Name',
              dt_width: null,
              dt_sortable: 1,
              dt_callback: null,
              dt_class: null,
              dt_rander: null,
              dt_rowgroup: 0,
              dt_filter: 1,
              dbfield: 1,
              info: null,
              title_lng: null,
              printview: null,
              printview_spl: 0,
            },
            {
              formid: 'items',
              sectionid: 'heading1',
              field: 'item_date',
              title: 'Date Of Import',
              colsize: 'col-6',
              type: 'string',
              component: 'datepicker',
              required: 0,
              sortno: 2,
              active: 1,
              formview: 1,
              listview: 1,
              selectqry: null,
              options: null,
              defaultvalue: null,
              addattrs: {},
              readonly: null,
              hidden: null,
              classes: null,
              inline: null,
              placeholder: null,
              hint: 'Please Enter Date of Import',
              dt_width: null,
              dt_sortable: 1,
              dt_callback: null,
              dt_class: null,
              dt_rander: null,
              dt_rowgroup: 0,
              dt_filter: 1,
              dbfield: 1,
              info: null,
              title_lng: null,
              printview: null,
              printview_spl: 0,
            },
            {
              formid: 'items',
              sectionid: 'heading1',
              field: 'description',
              title: 'Item Description',
              colsize: 'col-12',
              type: 'string',
              component: 'textarea',
              required: 0,
              sortno: 3,
              active: 1,
              formview: 1,
              listview: 1,
              selectqry: null,
              options: null,
              defaultvalue: null,
              addattrs: {},
              readonly: null,
              hidden: null,
              classes: null,
              inline: null,
              placeholder: null,
              hint: 'Please Enter Description',
              dt_width: null,
              dt_sortable: 1,
              dt_callback: null,
              dt_class: null,
              dt_rander: null,
              dt_rowgroup: 0,
              dt_filter: 1,
              dbfield: 1,
              info: null,
              title_lng: null,
              printview: null,
              printview_spl: 0,
            },
            {
              formid: 'items',
              sectionid: 'heading1',
              field: 'item_photo',
              title: 'Item Photo',
              colsize: 'col-3',
              type: 'string',
              component: 'image',
              required: 0,
              sortno: 4,
              active: 1,
              formview: 1,
              listview: 1,
              selectqry: null,
              options: null,
              defaultvalue: null,
              addattrs: {},
              readonly: null,
              hidden: null,
              classes: null,
              inline: null,
              placeholder: null,
              hint: 'Please Upload Photo',
              dt_width: null,
              dt_sortable: 1,
              dt_callback: null,
              dt_class: null,
              dt_rander: null,
              dt_rowgroup: 0,
              dt_filter: 1,
              dbfield: 1,
              info: null,
              title_lng: null,
              printview: null,
              printview_spl: 0,
            },
          ],
        },
        {
          formid: 'items',
          sectionid: 'heading2',
          title: 'heading2',
          readonly: null,
          colsize: 'col-12',
          classes: null,
          hint: null,
          sortno: 2,
          active: 1,
          columns: [
            {
              formid: 'items',
              sectionid: 'heading2',
              field: 'unit',
              title: 'Item Unit',
              colsize: 'col-6',
              type: 'string',
              component: 'input',
              required: 0,
              sortno: 1,
              active: 1,
              formview: 1,
              listview: 1,
              selectqry: null,
              options: null,
              defaultvalue: null,
              addattrs: {
                validation: {
                  pattern: '^.{1,50}$',
                  errorMessage: 'The input must be between 1 and 50 characters long. Thank You. :)',
                },
              },
              readonly: null,
              hidden: null,
              classes: null,
              inline: null,
              placeholder: null,
              hint: '',
              dt_width: null,
              dt_sortable: 1,
              dt_callback: null,
              dt_class: null,
              dt_rander: null,
              dt_rowgroup: 0,
              dt_filter: 1,
              dbfield: 1,
              info: null,
              title_lng: null,
              printview: null,
              printview_spl: 0,
            },
            {
              formid: 'items',
              sectionid: 'heading2',
              field: 'quantity',
              title: 'Item Quantity',
              colsize: 'col-6',
              type: 'number',
              component: 'number',
              required: 1,
              sortno: 2,
              active: 1,
              formview: 1,
              listview: 1,
              selectqry: null,
              options: null,
              defaultvalue: null,
              addattrs: {},
              readonly: null,
              hidden: null,
              classes: null,
              inline: null,
              placeholder: null,
              hint: 'Please Enter Quantity',
              dt_width: null,
              dt_sortable: 1,
              dt_callback: null,
              dt_class: null,
              dt_rander: null,
              dt_rowgroup: 0,
              dt_filter: 1,
              dbfield: 1,
              info: null,
              title_lng: null,
              printview: null,
              printview_spl: 0,
            },
          ],
        },
      ],
    },
  ],
  message: '',
};
