export const jsonTest = {
  data: [
    {
      formid: 'testform',
      title: 'Test Form',
      type: 'M',
      module: 'Testing',
      pkeys: null,
      pkeyid: null,
      model: null,
      extra_props: null,
      readonly: null,
      colsize: null,
      classes: null,
      hint: null,
      sortno: null,
      active: 1,
      formview: null,
      formfilter: null,
      description: null,
      formgroup: null,
      icon: null,
      sections: [
        {
          formid: 'testform',
          sectionid: 'testsection1',
          title: 'Section1',
          readonly: null,
          colsize: 'col-12',
          classes: null,
          hint: 'Section Hint',
          sortno: 1,
          active: 1,
          columns: [
            {
              formid: 'testform',
              sectionid: 'testsection1',
              field: 'name',
              title: 'Name',
              colsize: 'col-3',
              type: 'string',
              component: 'input',
              required: 1,
              sortno: 1,
              active: 1,
              formview: 1,
              listview: 1,
              selectqry: null,
              options: null,
              defaultvalue: 'nammememem',
              addattrs: null,
              readonly: null,
              hidden: null,
              classes: null,
              inline: null,
              placeholder: null,
              hint: 'Please Enter Name',
              dt_width: null,
              dt_sortable: 1,
              dt_callback: null,
              dt_class: null,
              dt_rander: null,
              dt_rowgroup: 0,
              dt_filter: 1,
              dbfield: null,
              info: null,
              title_lng: null,
              printview: null,
              printview_spl: 0,
            },
            {
              formid: 'testform',
              sectionid: 'testsection1',
              field: 'email',
              title: 'Name',
              colsize: 'col-3',
              type: 'string',
              component: 'input',
              required: 1,
              sortno: 2,
              active: 1,
              formview: 1,
              listview: 1,
              selectqry: null,
              options: null,
              defaultvalue: null,
              addattrs: null,
              readonly: null,
              hidden: null,
              classes: null,
              inline: null,
              placeholder: null,
              hint: 'Please Enter Email',
              dt_width: null,
              dt_sortable: 1,
              dt_callback: null,
              dt_class: null,
              dt_rander: null,
              dt_rowgroup: 0,
              dt_filter: 1,
              dbfield: null,
              info: null,
              title_lng: null,
              printview: null,
              printview_spl: 0,
            },
            {
              formid: 'testform',
              sectionid: 'testsection1',
              field: 'mobile',
              title: 'Mobile',
              colsize: 'col-3',
              type: 'number',
              component: 'number',
              required: 1,
              sortno: 3,
              active: 1,
              formview: 1,
              listview: 1,
              selectqry: null,
              options: null,
              defaultvalue: null,
              addattrs: null,
              readonly: null,
              hidden: null,
              classes: null,
              inline: null,
              placeholder: null,
              hint: null,
              dt_width: null,
              dt_sortable: 1,
              dt_callback: null,
              dt_class: null,
              dt_rander: null,
              dt_rowgroup: 0,
              dt_filter: 1,
              dbfield: null,
              info: null,
              title_lng: null,
              printview: null,
              printview_spl: 0,
            },
            {
              formid: 'testform',
              sectionid: 'testsection1',
              field: 'date',
              title: 'Date',
              colsize: 'col-3',
              type: 'date',
              component: 'datepicker',
              required: 1,
              sortno: 4,
              active: 1,
              formview: 1,
              listview: 1,
              selectqry: null,
              options: null,
              defaultvalue: null,
              addattrs: null,
              readonly: null,
              hidden: null,
              classes: null,
              inline: null,
              placeholder: null,
              hint: 'Please Enter Date',
              dt_width: null,
              dt_sortable: 1,
              dt_callback: null,
              dt_class: null,
              dt_rander: null,
              dt_rowgroup: 0,
              dt_filter: 1,
              dbfield: null,
              info: null,
              title_lng: null,
              printview: null,
              printview_spl: 0,
            },
            {
              formid: 'testform',
              sectionid: 'testsection1',
              field: 'active',
              title: 'Active',
              colsize: 'col-4',
              type: 'reactselect',
              component: 'reactselect',
              options: [
                { label: 'Option A', value: 'a' },
                { label: 'Option B', value: 'b' },
                { label: 'Option C', value: 'c' },
              ],
              required: 1,
              sortno: 5,
              active: 1,
              formview: 1,
              listview: 1,
              selectqry: null,
              defaultvalue: null,
              addattrs: null,
              readonly: null,
              hidden: null,
              classes: null,
              inline: null,
              placeholder: null,
              hint: null,
              dt_width: null,
              dt_sortable: 1,
              dt_callback: null,
              dt_class: null,
              dt_rander: null,
              dt_rowgroup: 0,
              dt_filter: 1,
              dbfield: null,
              info: null,
              title_lng: null,
              printview: null,
              printview_spl: 0,
            },
            {
              formid: 'testform',
              sectionid: 'testsection1',
              field: 'multiselect',
              title: 'Multi-select',
              colsize: 'col-4',
              type: 'multiselect',
              component: 'reactselect',
              required: 1,
              sortno: 7,
              active: 1,
              formview: 1,
              listview: 1,
              options: {
                data: [{}],
              },
              defaultvalue: null,
              addattrs: null,
              readonly: null,
              hidden: null,
              classes: null,
              inline: null,
              placeholder: null,
              hint: null,
              dt_width: null,
              dt_sortable: 1,
              dt_callback: null,
              dt_class: null,
              dt_rander: null,
              dt_rowgroup: 0,
              dt_filter: 1,
              dbfield: null,
              info: null,
              title_lng: null,
              printview: null,
              printview_spl: 0,
            },
            {
              formid: 'testform',
              sectionid: 'testsection1',
              field: 'fileinput',
              title: 'Fileinput',
              colsize: 'col-4',
              type: 'string',
              component: 'fileupload',
              required: 1,
              sortno: 8,
              active: 1,
              formview: 1,
              listview: 1,
              selectqry: null,
              options: null,
              defaultvalue: null,
              addattrs: null,
              readonly: null,
              hidden: null,
              classes: null,
              inline: null,
              placeholder: null,
              hint: null,
              dt_width: null,
              dt_sortable: 1,
              dt_callback: null,
              dt_class: null,
              dt_rander: null,
              dt_rowgroup: 0,
              dt_filter: 1,
              dbfield: null,
              info: null,
              title_lng: null,
              printview: null,
              printview_spl: 0,
            },
          ],
        },
        {
          formid: 'testform',
          sectionid: 'testsection2',
          title: 'Section2',
          readonly: null,
          colsize: 'col-12',
          classes: null,
          hint: null,
          sortno: null,
          active: 1,
          columns: [
            {
              formid: 'testform',
              sectionid: 'testsection2',
              field: 'captcha',
              title: 'Captcha',
              colsize: 'col-6',
              type: 'string',
              component: 'captcha',
              required: 1,
              sortno: 9,
              active: 1,
              formview: 1,
              listview: 1,
              selectqry: null,
              options: null,
              defaultvalue: null,
              addattrs: null,
              readonly: null,
              hidden: null,
              classes: null,
              inline: null,
              placeholder: null,
              hint: null,
              dt_width: null,
              dt_sortable: 1,
              dt_callback: null,
              dt_class: null,
              dt_rander: null,
              dt_rowgroup: 0,
              dt_filter: 1,
              dbfield: null,
              info: null,
              title_lng: null,
              printview: null,
              printview_spl: 0,
            },
            {
              formid: 'testform',
              sectionid: 'testsection2',
              field: 'password',
              title: 'Password',
              colsize: 'col-6',
              type: 'string',
              component: 'checkpassword',
              required: 1,
              sortno: 10,
              active: 1,
              formview: 1,
              listview: 1,
              selectqry: null,
              options: null,
              defaultvalue: null,
              addattrs: null,
              readonly: null,
              hidden: null,
              classes: null,
              inline: null,
              placeholder: null,
              hint: null,
              dt_width: null,
              dt_sortable: 1,
              dt_callback: null,
              dt_class: null,
              dt_rander: null,
              dt_rowgroup: 0,
              dt_filter: 1,
              dbfield: null,
              info: null,
              title_lng: null,
              printview: null,
              printview_spl: 0,
            },
            {
              formid: 'testform',
              sectionid: 'testsection2',
              field: 'textarea',
              title: 'TextArea',
              colsize: 'col-12',
              type: 'string',
              component: 'textarea',
              required: 1,
              sortno: 11,
              active: 1,
              formview: 1,
              listview: 1,
              selectqry: null,
              options: null,
              defaultvalue: null,
              addattrs: {
                rows: '2',
              },
              readonly: null,
              hidden: null,
              classes: null,
              inline: null,
              placeholder: null,
              hint: null,
              dt_width: null,
              dt_sortable: 1,
              dt_callback: null,
              dt_class: null,
              dt_rander: null,
              dt_rowgroup: 0,
              dt_filter: 1,
              dbfield: null,
              info: null,
              title_lng: null,
              printview: null,
              printview_spl: 0,
            },
          ],
        },
      ],
    },
  ],
  message: '',
};
